### ISSUE TITLE
Unable to send slack notification.

### ISSUE THREAD

**Issue by sambhure93** [MeilCli/slack-upload-file#438] opened 2022-05-16 05:47 UTC
we are getting following error while executing the GitHub action. can you please look into this.

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'tunnel'
Require stack:
- D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.9669 (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:10504:33)
    at __nccwpck_require__ (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:10643:43)
    at Object.6255 (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:1[13](https://github.com/patterninc/pattern-test-automation-workflows/runs/6445824372?check_suite_focus=true#step:14:13)2:29)
    at __nccwpck_require__ (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:10643:43)
    at Object.8041 (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:600:[23](https://github.com/patterninc/pattern-test-automation-workflows/runs/6445824372?check_suite_focus=true#step:14:23))
    at __nccwpck_require__ (D:\a\_actions\MeilCli\slack-upload-file\v1\dist\index.js:10643:43) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\a\\_actions\\MeilCli\\slack-upload-file\\v1\\dist\\index.js' ]
}

**Comment by MeilCli** [comment] 2022-05-16 05:55
@sambhure93 
I just published release that including fix that problem at 1 hour ago.
Please could you retry action?

I think, maybe fixed that by [v1.5.5](https://github.com/MeilCli/slack-upload-file/releases/tag/v1.5.5)

**Comment by MeilCli** [comment] 2022-05-16 06:06
sorry, I didn't fixed it...
I will fix soon

**Comment by MeilCli** [comment] 2022-05-16 06:10
@sambhure93 
I fixed [v1.5.6](https://github.com/MeilCli/slack-upload-file/releases/tag/v1.5.6). Please could you retry your action?

**Comment by MeilCli** [comment] 2022-05-21 11:59
I close this issue because I confirmed executing successful

**Closed by MeilCli** 2022-05-21 11:59 UTC
Labels: Bug
